theme: jekyll-theme-tactile
title: Clayman Asset Manager
url: 'https://www.clayman.app/'
baseurl: ''

docs_list_title: Clayman Help
docs:
- title: General Interface Guide
  url: help/interface.md
- title: General Create / Import Guide
  url: import.html
